const symbolMap = [
  { name: "Nifty 50", symbol: "NIFTY" },
  { name: "Nifty BANK", symbol: "BANKNIFTY" },
  { name: "Nifty FINANCIAL SERVICES", symbol: "FINNIFTY" },
  { name: "Nifty MIDCAP SELECT", symbol: "MIDCPNIFTY" },
  { name: "Nifty NEXT 50", symbol: "NIFTYNXT50" },
  { name: "ABB India Limited", symbol: "ABB" },
  { name: "ACC Limited", symbol: "ACC" },
  { name: "APL Apollo Tubes Limited", symbol: "APLAPOLLO" },
  { name: "AU Small Finance Bank Limited", symbol: "AUBANK" },
  { name: "Aarti Industries Limited", symbol: "AARTIIND" },
  { name: "Adani Energy Solutions Limited", symbol: "ADANIENSOL" },
  { name: "Adani Enterprises Limited", symbol: "ADANIENT" },
  { name: "Adani Green Energy Limited", symbol: "ADANIGREEN" },
  { name: "Adani Ports and Special Economic Zone Limited", symbol: "ADANIPORTS" },
  { name: "Adani Total Gas Limited", symbol: "ATGL" },
  { name: "Aditya Birla Capital Limited", symbol: "ABCAPITAL" },
  { name: "Aditya Birla Fashion and Retail Limited", symbol: "ABFRL" },
  { name: "Alkem Laboratories Limited", symbol: "ALKEM" },
  { name: "Ambuja Cements Limited", symbol: "AMBUJACEM" },
  { name: "Angel One Limited", symbol: "ANGELONE" },
  { name: "Apollo Hospitals Enterprise Limited", symbol: "APOLLOHOSP" },
  { name: "Apollo Tyres Limited", symbol: "APOLLOTYRE" },
  { name: "Ashok Leyland Limited", symbol: "ASHOKLEY" },
  { name: "Asian Paints Limited", symbol: "ASIANPAINT" },
  { name: "Astral Limited", symbol: "ASTRAL" },
  { name: "Aurobindo Pharma Limited", symbol: "AUROPHARMA" },
  { name: "Avenue Supermarts Limited", symbol: "DMART" },
  { name: "Axis Bank Limited", symbol: "AXISBANK" },
  { name: "BIRLASOFT LIMITED", symbol: "BSOFT" },
  { name: "BSE Limited", symbol: "BSE" },
  { name: "Bajaj Auto Limited", symbol: "BAJAJ-AUTO" },
  { name: "Bajaj Finance Limited", symbol: "BAJFINANCE" },
  { name: "Bajaj Finserv Limited", symbol: "BAJAJFINSV" },
  { name: "Balkrishna Industries Limited", symbol: "BALKRISIND" },
  { name: "Bandhan Bank Limited", symbol: "BANDHANBNK" },
  { name: "Bank of Baroda", symbol: "BANKBARODA" },
  { name: "Bank of India", symbol: "BANKINDIA" },
  { name: "Berger Paints (I) Limited", symbol: "BERGEPAINT" },
  { name: "Bharat Electronics Limited", symbol: "BEL" },
  { name: "Bharat Forge Limited", symbol: "BHARATFORG" },
  { name: "Bharat Heavy Electricals Limited", symbol: "BHEL" },
  { name: "Bharat Petroleum Corporation Limited", symbol: "BPCL" },
  { name: "Bharti Airtel Limited", symbol: "BHARTIARTL" },
  { name: "Biocon Limited", symbol: "BIOCON" },
  { name: "Bosch Limited", symbol: "BOSCHLTD" },
  { name: "Britannia Industries Limited", symbol: "BRITANNIA" },
  { name: "CESC Limited", symbol: "CESC" },
  { name: "CG Power and Industrial Solutions Limited", symbol: "CGPOWER" },
  { name: "Canara Bank", symbol: "CANBK" },
  { name: "Central Depository Services (India) Limited", symbol: "CDSL" },
  { name: "Chambal Fertilizers & Chemicals Limited", symbol: "CHAMBLFERT" },
  { name: "Cholamandalam Investment and Finance Company Limited", symbol: "CHOLAFIN" },
  { name: "Cipla Limited", symbol: "CIPLA" },
  { name: "Coal India Limited", symbol: "COALINDIA" },
  { name: "Coforge Limited", symbol: "COFORGE" },
  { name: "Colgate Palmolive (India) Limited", symbol: "COLPAL" },
  { name: "Computer Age Management Services Limited", symbol: "CAMS" },
  { name: "Container Corporation of India Limited", symbol: "CONCOR" },
  { name: "Crompton Greaves Consumer Electricals Limited", symbol: "CROMPTON" },
  { name: "Cummins India Limited", symbol: "CUMMINSIND" },
  { name: "Cyient Limited", symbol: "CYIENT" },
  { name: "DLF Limited", symbol: "DLF" },
  { name: "Dabur India Limited", symbol: "DABUR" },
  { name: "Dalmia Bharat Limited", symbol: "DALBHARAT" },
  { name: "Deepak Nitrite Limited", symbol: "DEEPAKNTR" },
  { name: "Delhivery Limited", symbol: "DELHIVERY" },
  { name: "Divi's Laboratories Limited", symbol: "DIVISLAB" },
  { name: "Dixon Technologies (India) Limited", symbol: "DIXON" },
  { name: "Dr. Reddy's Laboratories Limited", symbol: "DRREDDY" },
  { name: "ETERNAL LIMITED", symbol: "ETERNAL" },
  { name: "Eicher Motors Limited", symbol: "EICHERMOT" },
  { name: "Escorts Kubota Limited", symbol: "ESCORTS" },
  { name: "Exide Industries Limited", symbol: "EXIDEIND" },
  { name: "FSN E-Commerce Ventures Limited", symbol: "NYKAA" },
  { name: "GAIL (India) Limited", symbol: "GAIL" },
  { name: "GMR AIRPORTS LIMITED", symbol: "GMRAIRPORT" },
  { name: "Glenmark Pharmaceuticals Limited", symbol: "GLENMARK" },
  { name: "Godrej Consumer Products Limited", symbol: "GODREJCP" },
  { name: "Godrej Properties Limited", symbol: "GODREJPROP" },
  { name: "Granules India Limited", symbol: "GRANULES" },
  { name: "Grasim Industries Limited", symbol: "GRASIM" },
  { name: "HCL Technologies Limited", symbol: "HCLTECH" },
  { name: "HDFC Asset Management Company Limited", symbol: "HDFCAMC" },
  { name: "HDFC Bank Limited", symbol: "HDFCBANK" },
  { name: "HDFC Life Insurance Company Limited", symbol: "HDFCLIFE" },
  { name: "HFCL Limited", symbol: "HFCL" },
  { name: "Havells India Limited", symbol: "HAVELLS" },
  { name: "Hero MotoCorp Limited", symbol: "HEROMOTOCO" },
  { name: "Hindalco Industries Limited", symbol: "HINDALCO" },
  { name: "Hindustan Aeronautics Limited", symbol: "HAL" },
  { name: "Hindustan Copper Limited", symbol: "HINDCOPPER" },
  { name: "Hindustan Petroleum Corporation Limited", symbol: "HINDPETRO" },
  { name: "Hindustan Unilever Limited", symbol: "HINDUNILVR" },
  { name: "Hindustan Zinc Limited", symbol: "HINDZINC" },
  { name: "Housing & Urban Development Corporation Limited", symbol: "HUDCO" },
  { name: "ICICI Bank Limited", symbol: "ICICIBANK" },
  { name: "ICICI Lombard General Insurance Company Limited", symbol: "ICICIGI" },
  { name: "ICICI Prudential Life Insurance Company Limited", symbol: "ICICIPRULI" },
  { name: "IDFC First Bank Limited", symbol: "IDFCFIRSTB" },
  { name: "IIFL Finance Limited", symbol: "IIFL" },
  { name: "IRB Infrastructure Developers Limited", symbol: "IRB" },
  { name: "ITC Limited", symbol: "ITC" },
  { name: "Indian Bank", symbol: "INDIANB" },
  { name: "Indian Energy Exchange Limited", symbol: "IEX" },
  { name: "Indian Oil Corporation Limited", symbol: "IOC" },
  { name: "Indian Railway Catering And Tourism Corporation Limited", symbol: "IRCTC" },
  { name: "Indian Railway Finance Corporation Limited", symbol: "IRFC" },
  { name: "Indian Renewable Energy Development Agency Limited", symbol: "IREDA" },
  { name: "Indraprastha Gas Limited", symbol: "IGL" },
  { name: "Indus Towers Limited", symbol: "INDUSTOWER" },
  { name: "IndusInd Bank Limited", symbol: "INDUSINDBK" },
  { name: "Info Edge (India) Limited", symbol: "NAUKRI" },
  { name: "Infosys Limited", symbol: "INFY" },
  { name: "Inox Wind Limited", symbol: "INOXWIND" },
  { name: "InterGlobe Aviation Limited", symbol: "INDIGO" },
  { name: "JSW Energy Limited", symbol: "JSWENERGY" },
  { name: "JSW Steel Limited", symbol: "JSWSTEEL" },
  { name: "Jindal Stainless Limited", symbol: "JSL" },
  { name: "Jindal Steel & Power Limited", symbol: "JINDALSTEL" },
  { name: "Jio Financial Services Limited", symbol: "JIOFIN" },
  { name: "Jubilant Foodworks Limited", symbol: "JUBLFOOD" },
  { name: "KEI Industries Limited", symbol: "KEI" },
  { name: "KPIT Technologies Limited", symbol: "KPITTECH" },
  { name: "Kalyan Jewellers India Limited", symbol: "KALYANKJIL" },
  { name: "Kotak Mahindra Bank Limited", symbol: "KOTAKBANK" },
  { name: "L&T Finance Limited", symbol: "LTF" },
  { name: "LIC Housing Finance Limited", symbol: "LICHSGFIN" },
  { name: "LTIMindtree Limited", symbol: "LTIM" },
  { name: "Larsen & Toubro Limited", symbol: "LT" },
  { name: "Laurus Labs Limited", symbol: "LAURUSLABS" },
  { name: "Life Insurance Corporation Of India", symbol: "LICI" },
  { name: "Lupin Limited", symbol: "LUPIN" },
  { name: "MRF Limited", symbol: "MRF" },
  { name: "Macrotech Developers Limited", symbol: "LODHA" },
  { name: "Mahanagar Gas Limited", symbol: "MGL" },
  { name: "Mahindra & Mahindra Financial Services Limited", symbol: "M&MFIN" },
  { name: "Mahindra & Mahindra Limited", symbol: "M&M" },
  { name: "Manappuram Finance Limited", symbol: "MANAPPURAM" },
  { name: "Marico Limited", symbol: "MARICO" },
  { name: "Maruti Suzuki India Limited", symbol: "MARUTI" },
  { name: "Max Financial Services Limited", symbol: "MFSL" },
  { name: "Max Healthcare Institute Limited", symbol: "MAXHEALTH" },
  { name: "MphasiS Limited", symbol: "MPHASIS" },
  { name: "Multi Commodity Exchange of India Limited", symbol: "MCX" },
  { name: "Muthoot Finance Limited", symbol: "MUTHOOTFIN" },
  { name: "NBCC (India) Limited", symbol: "NBCC" },
  { name: "NCC Limited", symbol: "NCC" },
  { name: "NHPC Limited", symbol: "NHPC" },
  { name: "NMDC Limited", symbol: "NMDC" },
  { name: "NTPC Limited", symbol: "NTPC" },
  { name: "National Aluminium Company Limited", symbol: "NATIONALUM" },
  { name: "Nestle India Limited", symbol: "NESTLEIND" },
  { name: "Oberoi Realty Limited", symbol: "OBEROIRLTY" },
  { name: "Oil & Natural Gas Corporation Limited", symbol: "ONGC" },
  { name: "Oil India Limited", symbol: "OIL" },
  { name: "One 97 Communications Limited", symbol: "PAYTM" },
  { name: "Oracle Financial Services Software Limited", symbol: "OFSS" },
  { name: "PB Fintech Limited", symbol: "POLICYBZR" },
  { name: "PI Industries Limited", symbol: "PIIND" },
  { name: "PNB Housing Finance Limited", symbol: "PNBHOUSING" },
  { name: "Page Industries Limited", symbol: "PAGEIND" },
  { name: "Patanjali Foods Limited", symbol: "PATANJALI" },
  { name: "Persistent Systems Limited", symbol: "PERSISTENT" },
  { name: "Petronet LNG Limited", symbol: "PETRONET" },
  { name: "Pidilite Industries Limited", symbol: "PIDILITIND" },
  { name: "Piramal Enterprises Limited", symbol: "PEL" },
  { name: "Polycab India Limited", symbol: "POLYCAB" },
  { name: "Poonawalla Fincorp Limited", symbol: "POONAWALLA" },
  { name: "Power Finance Corporation Limited", symbol: "PFC" },
  { name: "Power Grid Corporation of India Limited", symbol: "POWERGRID" },
  { name: "Prestige Estates Projects Limited", symbol: "PRESTIGE" },
  { name: "Punjab National Bank", symbol: "PNB" },
  { name: "RBL Bank Limited", symbol: "RBLBANK" },
  { name: "REC Limited", symbol: "RECLTD" },
  { name: "Reliance Industries Limited", symbol: "RELIANCE" },
  { name: "SBI Cards and Payment Services Limited", symbol: "SBICARD" },
  { name: "SBI Life Insurance Company Limited", symbol: "SBILIFE" },
  { name: "SHREE CEMENT LIMITED", symbol: "SHREECEM" },
  { name: "SJVN Limited", symbol: "SJVN" },
  { name: "SRF Limited", symbol: "SRF" },
  { name: "Samvardhana Motherson International Limited", symbol: "MOTHERSON" },
  { name: "Shriram Finance Limited", symbol: "SHRIRAMFIN" },
  { name: "Siemens Limited", symbol: "SIEMENS" },
  { name: "Solar Industries India Limited", symbol: "SOLARINDS" },
  { name: "Sona BLW Precision Forgings Limited", symbol: "SONACOMS" },
  { name: "State Bank of India", symbol: "SBIN" },
  { name: "Steel Authority of India Limited", symbol: "SAIL" },
  { name: "Sun Pharmaceutical Industries Limited", symbol: "SUNPHARMA" },
  { name: "Supreme Industries Limited", symbol: "SUPREMEIND" },
  { name: "Syngene International Limited", symbol: "SYNGENE" },
  { name: "TATA CONSUMER PRODUCTS LIMITED", symbol: "TATACONSUM" },
  { name: "TITAGARH RAIL SYSTEMS LIMITED", symbol: "TITAGARH" },
  { name: "TVS Motor Company Limited", symbol: "TVSMOTOR" },
  { name: "Tata Chemicals Limited", symbol: "TATACHEM" },
  { name: "Tata Communications Limited", symbol: "TATACOMM" },
  { name: "Tata Consultancy Services Limited", symbol: "TCS" },
  { name: "Tata Elxsi Limited", symbol: "TATAELXSI" },
  { name: "Tata Motors Limited", symbol: "TATAMOTORS" },
  { name: "Tata Power Company Limited", symbol: "TATAPOWER" },
  { name: "Tata Steel Limited", symbol: "TATASTEEL" },
  { name: "Tata Technologies Limited", symbol: "TATATECH" },
  { name: "Tech Mahindra Limited", symbol: "TECHM" },
  { name: "The Federal Bank Limited", symbol: "FEDERALBNK" },
  { name: "The Indian Hotels Company Limited", symbol: "INDHOTEL" },
  { name: "The Phoenix Mills Limited", symbol: "PHOENIXLTD" },
  { name: "The Ramco Cements Limited", symbol: "RAMCOCEM" },
  { name: "Titan Company Limited", symbol: "TITAN" },
  { name: "Torrent Pharmaceuticals Limited", symbol: "TORNTPHARM" },
  { name: "Torrent Power Limited", symbol: "TORNTPOWER" },
  { name: "Trent Limited", symbol: "TRENT" },
  { name: "Tube Investments of India Limited", symbol: "TIINDIA" },
  { name: "UPL Limited", symbol: "UPL" },
  { name: "UltraTech Cement Limited", symbol: "ULTRACEMCO" },
  { name: "Union Bank of India", symbol: "UNIONBANK" },
  { name: "United Spirits Limited", symbol: "UNITDSPR" },
  { name: "Varun Beverages Limited", symbol: "VBL" },
  { name: "Vedanta Limited", symbol: "VEDL" },
  { name: "Vodafone Idea Limited", symbol: "IDEA" },
  { name: "Voltas Limited", symbol: "VOLTAS" },
  { name: "Wipro Limited", symbol: "WIPRO" },
  { name: "Yes Bank Limited", symbol: "YESBANK" },
  { name: "Zydus Lifesciences Limited", symbol: "ZYDUSLIFE" }
];